### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by naraesk** [softvis-research/jqa-php-plugin#1]
How do I have to compile this plugin? I invoked `mvn install` but only got a failure. See the attched log for details.
[maven.log](https://github.com/softvis-research/jqa-php-plugin/files/3128802/maven.log)

**Comment by naraesk** [comment]
Can be solved by updating the surefireplugin in the pom.xml to version 3.0.0-M3. Older versions are not compatible wtih jdk9+

**Comment by rmllr** [comment]
Thanks for the hint. I have changed the version of the maven-surefire-plugin accordingly (854d864841beab1788d5ac9e82c8b95d73067690).
